# BLUE Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-blue
  labels:
    app: aceest-fitness
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: blue
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: blue
    spec:
      containers:
      - name: aceest-fitness
        image: rahul-mtech/aceest-fitness:v1.2
        ports:
        - containerPort: 5000

---

# GREEN Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-green
  labels:
    app: aceest-fitness
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: green
    spec:
      containers:
      - name: aceest-fitness
        image: rahul-mtech/aceest-fitness:v1.3
        ports:
        - containerPort: 5000

---

# Service that points to GREEN (Live version)
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
spec:
  selector:
    app: aceest-fitness
    version: green
  ports:
  - port: 5000
    targetPort: 5000
